source "https://github.com/EkoCommunications/EkoMessagingSDKUIKit.git"

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpstraUIKitiOSSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AmityUIKit', '2.0.4'

  # Pods for UpstraUIKitiOSSample

  target 'UpstraUIKitiOSSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UpstraUIKitiOSSampleUITests' do
    # Pods for testing
  end

end
